import generated from "../data/section-visuals.generated.json";

/**
 * One visual specification per heading, derived from that heading's own prose.
 *
 * The JSON is written by scripts/build-section-visuals.mjs and regenerated by `npm run verify`,
 * so a heading that is renamed, renumbered or rewritten cannot leave a stale figure behind it.
 * Curated corrections live in scripts/section-visual-overrides.json and win over the derivation.
 */
export type PartVisualKind =
  | "stats"
  | "bars"
  | "gauge"
  | "donut"
  | "waffle"
  | "waterfall"
  | "bullet"
  | "stepper"
  | "timeline"
  | "playbook"
  | "matrix"
  | "table"
  | "quadrant"
  | "hub"
  | "checklist"
  | "chapter"
  | "quote"
  | "contrast"
  | "statement"
  | "shape";

export interface PartVisualSpec {
  id: string;
  tab: string;
  level: number;
  number: string;
  title: string;
  kind: PartVisualKind;
  data: Record<string, unknown>;
}

const SPECS = generated as unknown as Record<string, PartVisualSpec>;

export function partVisual(id: string | null | undefined): PartVisualSpec | null {
  if (!id) return null;
  return SPECS[id] ?? null;
}

export const PART_VISUAL_COUNT = Object.keys(SPECS).length;

/**
 * What each visual is for, in one phrase.
 *
 * It is the figure's subtitle — the handbook's rule that a chart states what is measured, not
 * just what it is — and it is also the label the chapter map uses for the glyph beside each part,
 * so a reader can see the shape of what is coming before they scroll into it.
 */
export const KIND_CAPTION: Record<PartVisualKind, string> = {
  stats: "Key figures",
  bars: "Ranked by size",
  gauge: "One figure, in scale",
  donut: "Share of the whole",
  waffle: "Composition, 100 squares",
  waterfall: "How the number is built",
  bullet: "Baseline against target",
  stepper: "In order",
  timeline: "In time",
  playbook: "Trigger and response",
  matrix: "Compared across criteria",
  table: "Interactive table",
  quadrant: "Likelihood against impact",
  hub: "One idea, its parts",
  checklist: "What this commits to",
  chapter: "What is in this part",
  quote: "The governing line",
  contrast: "Between two poles",
  statement: "The claim",
  shape: "The shape of the argument",
};
