import measured from "../data/section-heights.json";

import type { TabId } from "./heading-slug";

/**
 * How tall each section renders, measured on a 390 × 844 phone.
 *
 * The flow needs this twice, and both uses are about the same thing — the page being its real
 * height before it is its real content:
 *
 *   1. `contain-intrinsic-size` on every section, so the browser can skip laying out what is off
 *      screen without lying about how much room it takes. The CSS default of one flat value for
 *      all thirty sections made the document read as 42,000px when it is 480,000px.
 *   2. The space a streamed section holds open before its prose arrives.
 *
 * Regenerated by scripts/measure-section-heights.mjs. A stale value costs one scroll correction,
 * never a wrong figure, so it does not gate the build.
 */
const HEIGHTS = measured as Record<string, number>;

/** A section's measured height, or a word-count estimate where it has never been measured. */
export function sectionHeight(tabId: TabId, words: number): number {
  const known = HEIGHTS[tabId];
  if (known && known > 0) return known;
  return Math.round(Math.min(40000, Math.max(900, words * 8.7)));
}
