#!/usr/bin/env node
/**
 * Every deep link ever minted for this document must still land on a heading.
 *
 * The document is one route with fragment ids ("#analysis-sec-3-4"). A browser never sends the
 * fragment to the server, so a redirect in next.config cannot help. Only a client-side map can.
 * This script builds that map. It never hand-writes one.
 *
 * Inputs:
 *   lib/anchors/pre-rebuild.json  every id that existed before this rebuild, and every redirect
 *                                 edge the repo ever declared (frozen by scripts/rebuild/snapshot-anchors.mjs)
 *   lib/anchors/rebuild-moves.json ids this rebuild renumbered (written by scripts/rebuild/phase1.py)
 *   public/content/*.md           the headings that exist today
 *
 * Each old id follows its edges until it reaches a live heading. Where a chain dead-ends because
 * the part it named was folded into its parent, it climbs to the nearest live parent number in
 * the same route. An id that reaches nothing fails the build.
 *
 *     node --experimental-strip-types scripts/build-anchors.ts           # write lib/anchors/redirects.ts
 *     node --experimental-strip-types scripts/build-anchors.ts --check   # fail if it would change, or anything is orphaned
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = path.join(ROOT, "public", "content");
const OUT = path.join(ROOT, "lib", "anchors", "redirects.ts");
const CHECK = process.argv.includes("--check");

const LEADING = /^((?:\d+[A-Z]?(?:\.\d+)*|[A-G](?:\.\d+)+))\.?\s/;
const HEADING = /^(#{2,3})\s+(.+?)\s*$/;
const clean = (raw: string) =>
  raw.replace(/\*\((new|updated)\)\*/gi, "").replace(/\*\*/g, "").replace(/\*/g, "").replace(/`/g, "").trim();

/** Live ids, in document order per route, so "the route's first heading" is well defined. */
function liveIds(): Map<string, string[]> {
  const byRoute = new Map<string, string[]>();
  for (const file of fs.readdirSync(CONTENT).filter((f) => f.endsWith(".md")).sort()) {
    const route = file.replace(/\.md$/, "");
    const ids: string[] = [];
    let fence = false;
    for (const line of fs.readFileSync(path.join(CONTENT, file), "utf8").split("\n")) {
      if (/^\s*```/.test(line)) { fence = !fence; continue; }
      if (fence) continue;
      const m = HEADING.exec(line);
      if (!m) continue;
      const n = LEADING.exec(clean(m[2]));
      if (n) ids.push(`${route}-sec-${n[1].replace(/\./g, "-").toLowerCase()}`);
    }
    byRoute.set(route, ids);
  }
  return byRoute;
}

const byRoute = liveIds();
const live = new Set([...byRoute.values()].flat());
const pre = JSON.parse(fs.readFileSync(path.join(ROOT, "lib", "anchors", "pre-rebuild.json"), "utf8")) as {
  aliases: Record<string, string>;
  ids: string[];
  edges: Record<string, string>;
};
const moves = JSON.parse(fs.readFileSync(path.join(ROOT, "lib", "anchors", "rebuild-moves.json"), "utf8")) as Record<string, string>;

function climb(id: string): string | null {
  const [route, slug] = id.split("-sec-");
  const parts = slug.split("-");
  while (parts.length > 1) {
    parts.pop();
    const candidate = `${route}-sec-${parts.join("-")}`;
    if (live.has(candidate)) return candidate;
    const moved = moves[candidate];
    if (moved && live.has(moved)) return moved;
  }
  return null;
}

function resolve(start: string): string | null {
  let id = start;
  const seen = new Set<string>();
  while (!seen.has(id)) {
    if (live.has(id)) return id;
    seen.add(id);
    const next = moves[id] ?? pre.edges[id];
    if (next) { id = next; continue; }
    const parent = climb(id);
    if (parent) return parent;
    // A retired tab that served a file still on disk: the same heading, under the file's route.
    const [tab, slug] = id.split("-sec-");
    const alias = pre.aliases[tab];
    if (alias) { id = `${alias}-sec-${slug}`; continue; }
    const route = id.split("-sec-")[0];
    const first = byRoute.get(route)?.[0];
    return first ?? null;
  }
  return null;
}

const redirects: Record<string, string> = {};
const orphans: string[] = [];
const everyOld = new Set([...pre.ids, ...Object.keys(pre.edges), ...Object.keys(moves)]);
for (const id of [...everyOld].sort()) {
  if (live.has(id)) continue;
  const target = resolve(id);
  if (target) redirects[id] = target;
  else orphans.push(id);
}

const body =
  "// GENERATED by scripts/build-anchors.ts. Do not edit: change the content or lib/anchors/*.json and rebuild.\n" +
  "//\n" +
  "// Old deep-link id -> the live heading it now lands on. Every id that existed before the 2026\n" +
  "// rebuild is either a live heading or a key here; the build fails otherwise.\n" +
  "export const ANCHOR_REDIRECTS: Record<string, string> = " +
  JSON.stringify(redirects, null, 1) +
  ";\n";

if (orphans.length) {
  console.error(`build-anchors: ${orphans.length} pre-rebuild id(s) land on nothing:`);
  for (const id of orphans.slice(0, 20)) console.error(`  - ${id}`);
  process.exit(1);
}
if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== body) {
    console.error("build-anchors: lib/anchors/redirects.ts is stale. Run: node --experimental-strip-types scripts/build-anchors.ts");
    process.exit(1);
  }
} else {
  fs.writeFileSync(OUT, body);
}
console.log(`build-anchors: ${live.size} live headings, ${Object.keys(redirects).length} redirects, 0 orphans`);
