/**
 * Old heading -> new heading. Every addressable heading in the document, mapped once.
 *
 * Read as: "<old file> <old number>": ["<new route>", "<new number>", "<new title or null to keep>"]
 *
 * A null title means the heading keeps the words it has; the brief only renumbers it. A string
 * replaces the title, and every replacement here is <new_structure>'s own wording, which the brief
 * calls final copy.
 *
 * WHAT THIS FILE IS NOT. It is not where prose is cut. Phase 1 moves whole blocks and renumbers
 * them; <cuts_and_moves> and <consistency_fixes> run afterwards against a document that is already
 * in its new shape. A block the brief eventually splits across two homes is placed here at its
 * PRIMARY home with a `SPLIT` note, so Phase 2 has a list rather than a memory.
 *
 * A "-" target means the block is cut by <cuts_and_moves>. Phase 1 still moves it, to the route
 * named after the dash, so that nothing disappears before the phase that is allowed to remove it.
 */

export const HEADING_MAP = {
  // ---------------------------------------------------------------- Cover and Annex G
  "cover 1.1":  ["cover", "", "Prepared for, prepared by, and on what terms"],
  "cover 1.2":  ["annex-terms", "G.1", "Confidentiality and use"],
  "cover 1.3":  ["objectives", "1.4", "How this proposal is built"],
  "decision 0.5": ["annex-terms", "G.2", "Who this is for, and on what terms"],

  // ---------------------------------------------------------------- 1. Objectives
  "objectives 4.1":   ["objectives", "1.1", "The goal: the Wiper ticket first, the county second"],
  "objectives 4.2":   ["objectives", "1.3", "Five objectives for the digital operation"],
  "objectives 4.1.1": ["objectives", "1.3.1", "Be known where he isn't yet"],
  "objectives 4.1.2": ["objectives", "1.3.2", "Turn his record into visible proof"],   // REWRITE: its target was a poll share
  "objectives 4.2.1": ["objectives", "1.3.4", "Give every post a voter, a ward and a reason"],
  "objectives 4.2.2": ["objectives", "1.3.3", "Build a direct line to the voters the internet doesn't reach"],
  "objectives 4.2.3": ["objectives", "1.3.5", "Hold the home base while Kitui Central runs its own race"],
  "summary 2.2":      ["objectives", "1.2", "The two deadlines"],  // SPLIT: the calendar stays, the slider and poll table are cut in Phase 2
  "measurement 11.1.3": ["objectives", "1.5", "How success will be judged"],

  // ---------------------------------------------------------------- 2. The Data
  "situation 3.3":     ["data", "2.0", "What the official record shows"],
  "situation 3.3.3":   ["data", "2.1", "The electorate"],
  "situation 3.3.6":   ["data", "2.2", "How Kitui has voted"],
  "situation 3.1":     ["data", "2.3", "The nomination rules and the calendar"],
  "situation 3.1.1":   ["data", "2.3.1", null],
  "situation 3.1.2":   ["data", "2.3.2", null],
  "situation 3.3.5":   ["data", "2.4", "The county's people and economy"],            // SPLIT: connectivity half -> 2.6
  "situation 3.3.4":   ["data", "2.5", "The budget the next governor runs"],
  "reach 3.6.1":       ["data", "2.6", "How people get information"],                  // SPLIT: the ceiling -> 3.8
  "reach 3.7":         ["data", "2.7", "Who owns the airwaves"],
  "reach 3.7.1":       ["data", "2.7.1", null],
  "situation 3.3.1":   ["data", "2.8", "Dr. Mulu's public record"],                    // SPLIT: the positioning use -> 4.1
  "presence 1A.2.4":   ["data", "2.9", "His channels today, and his rivals'"],

  // ---------------------------------------------------------------- 3. The Analysis
  "arithmetic 3.4":    ["analysis", "3.0", "The winning number, and why he isn't yet reaching it"],
  "arithmetic 3.4.1":  ["analysis", "3.1", "The number it takes"],
  "arithmetic 3.4.2":  ["analysis", "3.2", "Where the votes are"],
  "arithmetic 3.4.4":  ["analysis", "3.2.1", "The constituencies that decide it"],
  "arithmetic 3.4.3":  ["analysis", "3.3", "Four routes to the number"],
  "arithmetic 3.4.5":  ["analysis", "3.4", "Where he is known and where he isn't"],
  "situation 3.3.2":   ["analysis", "3.5", "What his rivals have already proven"],      // SPLIT: eligibility -> 5.8
  "situation 3.1.5a":  ["analysis", "3.6", "Where party loyalty won't carry him"],
  "arithmetic 3.5":    ["analysis", "3.7", "The three regions"],
  "arithmetic 3.5.1":  ["analysis", "3.7.1", null],
  "arithmetic 3.5.2":  ["analysis", "3.7.2", null],
  "arithmetic 3.5.3":  ["analysis", "3.7.3", null],
  "reach 3.6":         ["analysis", "3.8", "What each channel can physically reach"],
  "reach 3.6.2":       ["analysis", "3.8.1", "The offline majority, and the infrastructure that reaches it"],
  "presence 1A.2.5":   ["analysis", "3.9", "What his current presence shows"],          // SPLIT: the six fixes -> 4.7
  "presence 1A.5":     ["analysis", "3.9.1", "What the audit produces"],
  "arithmetic 3.4.6":  ["analysis", "3.10", "What the data can't yet tell us"],
  "audiences 5.3":     ["analysis", "3.10.1", "Segment research still outstanding"],
  "presence 1A.4":     ["analysis", "3.11", "The diagnosis, and the evidence that could overturn it"],

  // ---------------------------------------------------------------- 4. The Strategy
  "approach 6.1":      ["strategy", "4.1", "The position"],
  "approach 6.1.1":    ["strategy", "4.1.1", null],
  "approach 6.1.2":    ["strategy", "4.1.2", null],
  "approach 6.1.3":    ["strategy", "4.1.3", null],
  "approach 6.2":      ["strategy", "4.1.4", "The four strategic pillars"],
  "approach 6.2.1":    ["strategy", "4.1.5", "The four campaign pillars in practice"],
  "approach 6.3":      ["strategy", "4.1.6", "The six campaign themes"],
  "arithmetic 3.5.4":  ["strategy", "4.2", "Where the effort goes"],
  "audiences 5.0":     ["strategy", "4.3", "Who we are trying to move"],
  "audiences 5.1":     ["strategy", "4.3.1", "The six voter segments"],
  "audiences 5.1.1":   ["strategy", "4.3.2", null],
  "audiences 5.1.2":   ["strategy", "4.3.3", null],
  "audiences 5.1.3":   ["strategy", "4.3.4", null],
  "audiences 5.1.4":   ["strategy", "4.3.5", null],
  "audiences 5.1.5":   ["strategy", "4.3.6", null],
  "audiences 5.1.6":   ["strategy", "4.3.7", null],
  "audiences 5.2":     ["strategy", "4.3.8", "Segment sizing, and the evidence for it"],
  "messaging 7.1":     ["strategy", "4.4", "What we say, and in which language"],
  "messaging 7.1.1":   ["strategy", "4.4.1", null],
  "messaging 7.1.4":   ["strategy", "4.4.2", "Counter-messaging against disinformation"],
  "messaging 7.2":     ["strategy", "4.4.3", "Persuasion principles and message discipline"],
  "messaging 7.2.1":   ["strategy", "4.4.4", "Framing true claims, transparently"],
  "messaging 7.2.2":   ["strategy", "4.4.5", "The principles we apply"],
  "messaging 7.2.3":   ["strategy", "4.4.6", "Framing, worked through in examples"],
  "messaging 7.3":     ["strategy", "4.4.7", "Language, register and dialect"],
  "messaging 7.3.1":   ["strategy", "4.4.8", "Which language reaches which voters, on which channel"],
  "messaging 7.3.2":   ["strategy", "4.4.9", "Register, dialect and the discipline it takes"],
  "messaging 7.3.3":   ["strategy", "4.4.10", "The production and quality-control pipeline"],
  "messaging 7.3.4":   ["strategy", "4.4.11", "Channel-by-language deployment"],
  "engine 6A.1":       ["strategy", "4.5", "What gets published"],
  "engine 6A.1.1":     ["strategy", "4.5.1", null],
  "engine 6A.1.2":     ["strategy", "4.5.2", null],
  "engine 6A.1.3":     ["strategy", "4.5.3", null],
  "engine 6A.1.4":     ["strategy", "4.5.4", null],
  "engine 6A.2":       ["strategy", "4.5.5", "One week, before and after"],
  "reach 3.6.3":       ["strategy", "4.6", "Which channel does which job"],
  "reach 3.7.2":       ["strategy", "4.6.1", "The gatekeeper bottleneck"],
  "presence 1A.2.1":   ["strategy", "4.7", "Fix first: six profile corrections"],        // the structural question + the fixes
  "presence 1A.2.2":   ["implementation", "5.3.1", "The measurement set"],
  "presence 1A.2.3":   ["implementation", "5.3.2", "The window"],
  "presence 1A.2":     ["implementation", "5.3.3", "What is measured"],
  "presence 1A.1":     ["implementation", "5.3.4", "Why this comes first"],
  "presence 1A.3":     ["implementation", "5.3.5", "Method"],
  "presence 1A.6":     ["implementation", "5.3.6", "What this section is not"],

  // ---------------------------------------------------------------- 5. Implementation
  "scope 8.0":         ["implementation", "5.1", "Who owns what: fourteen workstreams"],
  "decision 0.3":      ["implementation", "5.1.1", "Who owns what"],
  "scope 8.0.1":       ["implementation", "5.1.2", "The fourteen, by owner"],
  "scope 8.0.2":       ["implementation", "5.1.3", "What is outside this scope"],
  "scope 8.0.3":       ["implementation", "5.1.4", "How the levels change what runs"],
  "scope-platforms 8.1":   ["implementation", "5.1.5", "Scope summary and workstream boundaries"],
  "scope-platforms 8.1.1": ["implementation", "5.1.6", "Digital infrastructure, brand and civic content"],
  "scope-platforms 8.1.2": ["implementation", "5.1.7", "Growth, field advertising and reputation operations"],
  "roadmap 9.1":       ["implementation", "5.4", "The phases to August 2027"],
  "roadmap 9.1.1":     ["implementation", "5.3", "The first four weeks"],
  "roadmap 9.1.2":     ["implementation", "5.3.7", "Phase 0: Instrumentation — Weeks 4–10 from signature"],
  "roadmap 9.1.3":     ["implementation", "5.4.1", null],
  "roadmap 9.1.4":     ["implementation", "5.4.2", null],
  "roadmap 9.1.5":     ["implementation", "5.4.3", null],
  "roadmap 9.1.6":     ["implementation", "5.4.4", "Post-election"],
  "roadmap 9.2":       ["implementation", "5.4.5", "Coalition and endorsement sequencing"],
  "roadmap 9.2.1":     ["implementation", "5.4.6", "The principle behind the sequence"],
  "roadmap 9.2.2":     ["implementation", "5.4.7", "The sequenced calendar"],
  "roadmap 9.2.3":     ["implementation", "5.4.8", "Managing endorsements"],
  "roadmap 9.2.4":     ["implementation", "5.4.9", "Coalition KPIs"],

  // 5.2.1-5.2.14 — the fourteen workstreams, one h2 each, across four routes.
  "scope-platforms 8.2":  ["workstreams-platforms", "5.2.1", "Workstream 1 — Owned platforms and the service-delivery tracker"],
  "scope-platforms 8.2.1": ["workstreams-platforms", "5.2.1.1", null],
  "scope-platforms 8.2.2": ["workstreams-platforms", "5.2.1.2", null],
  "scope-platforms 8.2.3": ["workstreams-platforms", "5.2.1.3", null],
  "scope-platforms 8.2.4": ["workstreams-platforms", "5.2.1.4", null],
  "scope-platforms 8.2.5": ["workstreams-platforms", "5.2.1.5", null],
  "scope-platforms 8.2.6": ["workstreams-platforms", "5.2.1.6", null],
  "scope-platforms 8.2.7": ["workstreams-platforms", "5.2.1.7", null],
  "scope-platforms 8.3":  ["workstreams-platforms", "5.2.2", "Workstream 2 — The content brief and asset governance"],
  "scope-platforms 8.3.1": ["workstreams-platforms", "5.2.2.1", null],
  "scope-platforms 8.3.2": ["workstreams-platforms", "5.2.2.2", null],
  "scope-platforms 8.3.3": ["workstreams-platforms", "5.2.2.3", null],
  "scope-platforms 8.3.4": ["workstreams-platforms", "5.2.2.4", null],
  "scope-platforms 8.3.5": ["workstreams-platforms", "5.2.2.5", null],
  "scope-platforms 8.3.6": ["workstreams-platforms", "5.2.2.6", null],
  "scope-platforms 8.4":  ["workstreams-platforms", "5.2.3", "Workstream 3 — Creative testing and AI assistance"],
  "scope-platforms 8.4.1": ["workstreams-platforms", "5.2.3.1", null],
  "scope-platforms 8.4.2": ["workstreams-platforms", "5.2.3.2", null],
  "scope-platforms 8.4.3": ["workstreams-platforms", "5.2.3.3", null],
  "scope-platforms 8.4.4": ["workstreams-platforms", "5.2.3.4", null],
  "scope-platforms 8.5":  ["workstreams-platforms", "5.2.4", "Workstream 4 — Accessibility and inclusion"],
  "scope-platforms 8.5.1": ["workstreams-platforms", "5.2.4.1", null],
  "scope-platforms 8.5.2": ["workstreams-platforms", "5.2.4.2", null],
  "scope-platforms 8.5.3": ["workstreams-platforms", "5.2.4.3", null],
  "scope-platforms 8.5.4": ["workstreams-platforms", "5.2.4.4", null],
  "scope-platforms 8.5.5": ["workstreams-platforms", "5.2.4.5", null],

  "scope-media 8.6":   ["workstreams-media", "5.2.5", "Workstream 5 — Platform tactics and paid media"],
  "scope-media 8.7":   ["workstreams-media", "5.2.6", "Workstream 6 — Earned media, journalists and debates"],
  "scope-media 8.7.1": ["workstreams-media", "5.2.6.1", null],
  "scope-media 8.7.2": ["workstreams-media", "5.2.6.2", null],
  "scope-media 8.7.3": ["workstreams-media", "5.2.6.3", null],
  "scope-media 8.7.4": ["workstreams-media", "5.2.6.4", null],
  "scope-media 8.7.5": ["workstreams-media", "5.2.6.5", null],
  "scope-media 8.7.6": ["workstreams-media", "5.2.6.6", null],
  "scope-media 8.7.7": ["workstreams-media", "5.2.6.7", null],
  "scope-media 8.7.8": ["workstreams-media", "5.2.6.8", null],

  "scope-ground 8.8":    ["workstreams-ground", "5.2.7", "Workstream 7 — Ground-digital integration"],
  "scope-ground 8.8.1":  ["workstreams-ground", "5.2.7.1", null],
  "scope-ground 8.8.2":  ["workstreams-ground", "5.2.7.2", null],
  "scope-ground 8.8.3":  ["workstreams-ground", "5.2.7.3", null],
  "scope-ground 8.8.4":  ["workstreams-ground", "5.2.7.4", null],
  "scope-ground 8.9":    ["workstreams-ground", "5.2.8", "Workstream 8 — The field-to-digital loop"],
  "scope-ground 8.9.1":  ["workstreams-ground", "5.2.8.1", null],
  "scope-ground 8.9.2":  ["workstreams-ground", "5.2.8.2", null],
  "scope-ground 8.10":   ["workstreams-ground", "5.2.9", "Workstream 9 — What Firefly operates: SMS, USSD and voice"],
  "scope-ground 8.10.1": ["workstreams-ground", "5.2.9.1", null],
  "scope-ground 8.10.2": ["workstreams-ground", "5.2.9.2", null],
  "scope-ground 8.10.3": ["workstreams-ground", "5.2.9.3", null],
  "scope-ground 8.10.4": ["workstreams-ground", "5.2.9.4", null],
  "scope-ground 8.10.5": ["workstreams-ground", "5.2.9.5", null],
  "scope-ground 8.10.6": ["workstreams-ground", "5.2.9.6", null],
  "scope-ground 8.11":   ["workstreams-ground", "5.2.10", "Workstream 10 — Digital organising and volunteers"],
  "scope-ground 8.11.1": ["workstreams-ground", "5.2.10.1", null],
  "scope-ground 8.11.2": ["workstreams-ground", "5.2.10.2", null],
  "scope-ground 8.11.3": ["workstreams-ground", "5.2.10.3", null],
  "scope-ground 8.11.4": ["workstreams-ground", "5.2.10.4", null],
  "scope-ground 8.11.5": ["workstreams-ground", "5.2.10.5", null],

  "scope-data 8.12":   ["workstreams-data", "5.2.11", "Workstream 11 — The data layer"],
  "scope-data 8.12.1": ["workstreams-data", "5.2.11.1", null],
  "scope-data 8.12.2": ["workstreams-data", "5.2.11.2", null],
  "scope-data 8.13":   ["workstreams-data", "5.2.12", "Workstream 12 — Predictive voter modelling"],
  "scope-data 8.13.1": ["workstreams-data", "5.2.12.1", null],
  "scope-data 8.13.2": ["workstreams-data", "5.2.12.2", null],
  "scope-data 8.13.3": ["workstreams-data", "5.2.12.3", null],
  "scope-data 8.13.4": ["workstreams-data", "5.2.12.4", null],
  "scope-data 8.13.5": ["workstreams-data", "5.2.12.5", null],
  "scope-data 8.13.6": ["workstreams-data", "5.2.12.6", null],
  "scope-data 8.13.7": ["workstreams-data", "5.2.12.7", null],
  "scope-data 8.14":   ["workstreams-data", "5.2.13", "Workstream 13 — The technology stack"],
  "scope-data 8.14.1": ["workstreams-data", "5.2.13.1", null],
  "scope-data 8.14.2": ["workstreams-data", "5.2.13.2", null],
  "scope-data 8.14.3": ["workstreams-data", "5.2.13.3", null],
  "scope-data 8.15":   ["workstreams-data", "5.2.14", "Workstream 14 — Analytics and attribution"],
  "scope-data 8.15.1": ["workstreams-data", "5.2.14.1", null],
  "scope-data 8.15.2": ["workstreams-data", "5.2.14.2", null],
  "scope-data 8.15.3": ["workstreams-data", "5.2.14.3", null],
  "scope-data 8.15.4": ["workstreams-data", "5.2.14.4", null],

  // 5.5-5.9 on their own route
  "deliverables 10.1":   ["delivery", "5.5", "What Dr. Mulu receives, and how often"],
  "deliverables 10.1.1": ["delivery", "5.5.1", "The three scope levels"],
  "deliverables 10.1.2": ["delivery", "5.5.2", "The scope levels compared"],
  "deliverables 10.2":   ["delivery", "5.5.3", "The deliverables schedule"],
  "summary 2.4":         ["delivery", "5.5.4", "What this proposal commits to"],
  "measurement 11.1":    ["delivery", "5.6", "How progress is measured"],
  "measurement 11.1.1":  ["delivery", "5.6.1", null],
  "measurement 11.1.2":  ["delivery", "5.6.2", null],
  "measurement 11.2":    ["delivery", "5.6.3", "Indicators, and why these"],
  "measurement 11.2.0":  ["delivery", "5.6.4", "Re-anchored: recognition and persuasion where he is least known"],
  "measurement 11.2.1":  ["delivery", "5.6.5", "The research programme"],
  "measurement 11.2.2":  ["delivery", "5.6.6", "The service-delivery performance tracker"],
  "measurement 11.2.3":  ["delivery", "5.6.7", "Why vanity metrics are excluded"],
  "measurement 11.2.4":  ["delivery", "5.6.8", "Performance governance and executive escalation"],
  "measurement 11.3":    ["delivery", "5.6.9", "The Kitui message lab"],
  "measurement 11.3.1":  ["delivery", "5.6.10", "Rationale, structure and zone coverage"],
  "measurement 11.3.2":  ["delivery", "5.6.11", "Qualitative hypotheses, feedback loops and KPIs"],
  "governance 12.1":     ["delivery", "5.7", "How decisions are made"],
  "governance 12.1.1":   ["delivery", "5.7.1", "Operating rhythm, tooling and reporting lines"],
  "governance 12.1.2":   ["delivery", "5.7.2", "Who does what, in one table"],
  "governance 12.3":     ["delivery", "5.7.3", "Decision rights and content approval"],
  "governance 12.5":     ["delivery", "5.7.4", "Data ethics, privacy and the data charter"],
  "governance 12.5.1":   ["delivery", "5.7.5", "The standard we hold ourselves to"],
  "governance 12.5.2":   ["delivery", "5.7.6", "The regulatory environment as it stands"],
  "governance 12.5.3":   ["delivery", "5.7.7", "Compliance measures"],
  "governance 12.5.4":   ["delivery", "5.7.8", "The Digital Ethics and Data Charter"],
  "governance 12.5.5":   ["delivery", "5.7.9", "The compliance sign-off gate"],
  "risk 13.0":           ["delivery", "5.8", "Risks and responses"],
  "risk 13.1":           ["delivery", "5.8.1", "Rapid-response protocol and opposition handling"],
  "risk 13.1.1":         ["delivery", "5.8.2", "What we monitor, and how threats reach us"],
  "risk 13.1.5":         ["delivery", "5.8.3", "Staying inside defamation law"],
  "risk 13.2":           ["delivery", "5.8.4", "The digital war room"],
  "risk 13.2.1":         ["delivery", "5.8.5", "War room operating model, shift coverage and dashboard view"],
  "risk 13.3":           ["delivery", "5.8.6", "Cybersecurity and manipulated media"],
  "risk 13.3.5":         ["delivery", "5.8.7", "The deepfake and manipulated media protocol"],
  "risk 13.4":           ["delivery", "5.8.8", "Competitor monitoring"],
  "risk 13.4.1":         ["delivery", "5.8.9", "Public sources only, and the line we do not cross"],
  "risk 13.4.4":         ["delivery", "5.8.10", "Reading the current field"],
  "risk 13.5":           ["delivery", "5.8.11", "Statutory and regulatory compliance"],
  "risk 13.5.1":         ["delivery", "5.8.12", "The IEBC nomination and clearance checklist"],
  "risk 13.5.2":         ["delivery", "5.8.13", "Data protection and election offences liability"],
  "situation 3.1.6":     ["delivery", "5.8.14", "If it becomes a delegate primary"],
  "structure 14.1":      ["delivery", "5.9", "How the work is staffed"],
  "structure 14.2":      ["delivery", "5.9.1", "A lean core with a defined surge"],
  "structure 14.3":      ["delivery", "5.9.2", "The core team, retained throughout"],
  "structure 14.4":      ["delivery", "5.9.3", "Surge roles, activated by phase and scope level"],
  "structure 14.5":      ["delivery", "5.9.4", "Leadership roles and who owns what"],
  "structure 14.6":      ["delivery", "5.9.5", "Reporting lines"],
  "structure 14.7":      ["delivery", "5.9.6", "How the existing team is assessed and upskilled"],

  // ---------------------------------------------------------------- 6. Next Steps
  "assumptions 15.1":  ["nextsteps", "6.1", "What this needs from the campaign"],
  "decision 0.4":      ["nextsteps", "6.1.1", "What this asks of the campaign"],
  "assumptions 15.2":  ["nextsteps", "6.2", "Open items"],
  "assumptions 15.3":  ["nextsteps", "6.2.1", "Assumptions this proposal rests on"],
  "nextsteps 16.1":    ["nextsteps", "6.3", "The decision: one week and one export"],
  "nextsteps 16.2":    ["nextsteps", "6.3.1", "The ask"],
  "decision 0.1":      ["nextsteps", "6.3.2", "The ask, in full"],

  // ---------------------------------------------------------------- Annexes
  "annex-evidence 3.2":   ["annex-evidence", "A.1", "Evidence standard: provenance and source tiers"],
  "annex-evidence 3.2.1": ["annex-evidence", "A.1.1", null],
  "annex-evidence 3.2.2": ["annex-evidence", "A.1.2", null],
  "annex-evidence 3.2.3": ["annex-evidence", "A.1.3", null],
  "annex-evidence 3.2.4": ["annex-evidence", "A.1.4", null],
  "annex-county 3.3.7":   ["annex-county", "B.2", "County money and the audit record"],
  "annex-county 3.3.8":   ["annex-county", "B.3", "Drought, food security and climate pressure"],
  "annex-county 3.3.9":   ["annex-county", "B.4", "Mui Basin coal and the displaced communities"],
  "annex-county 3.3.10":  ["annex-county", "B.5", "Each rival, and the legal ground to be careful on"],
  "annex-messages 7.1.2": ["annex-messages", "D.1", "Message assignment by segment"],
  "annex-messages 7.1.3": ["annex-messages", "D.2", "Message assignment by channel"],
  "annex-cadence 12.2":   ["annex-cadence", "E.1", "Cadence and the meeting rhythm"],
  "annex-cadence 12.4":   ["annex-cadence", "E.2", "The escalation path"],
  "annex-runbooks 13.1.2": ["annex-runbooks", "F.1", "The four-tier response decision tree"],
  "annex-runbooks 13.1.3": ["annex-runbooks", "F.2", "Response times, by channel"],
  "annex-runbooks 13.1.4": ["annex-runbooks", "F.3", "Holding positions, pre-drafted"],
  "annex-runbooks 13.2.2": ["annex-runbooks", "F.4", "Monitoring tools"],
  "annex-runbooks 13.2.3": ["annex-runbooks", "F.5", "Rapid-response protocol and pre-approved message library"],
  "annex-runbooks 13.2.4": ["annex-runbooks", "F.6", "Red-team drills"],
  "annex-runbooks 13.3.1": ["annex-runbooks", "F.7", "The threat model"],
  "annex-runbooks 13.3.2": ["annex-runbooks", "F.8", "Account security baseline"],
  "annex-runbooks 13.3.3": ["annex-runbooks", "F.9", "Phishing awareness"],
  "annex-runbooks 13.3.4": ["annex-runbooks", "F.10", "The incident response plan"],
  "annex-runbooks 13.4.2": ["annex-runbooks", "F.11", "Competitor monitoring tools"],
  "annex-runbooks 13.4.3": ["annex-runbooks", "F.12", "Competitive intelligence outputs and rapid alerts"],

  // ---------------------------------------------------------------- Annex C, and what is cut
  // The polls leave the argument and become a reference annex, per non-negotiable 1.
  "situation 3.1.5":   ["annex-polls", "C.1", "The published rounds, and what each one measured"],
  "situation 3.1.3":   ["annex-polls", "C.2", "What the poll would measure"],           // CUT in Phase 2; one line may survive in 5.8
  "situation 3.1.4":   ["annex-polls", "C.3", "Kitui Central's weight in the vote"],    // CUT in Phase 2
  // Cut outright by <cuts_and_moves>. Moved to their new home first so Phase 2 removes prose
  // from a document already in its new shape, and nothing vanishes in a phase that only moves.
  "decision 0.2":      ["objectives", "1.2.1", "Why the answer cannot be \"later\""],   // CUT: urgency restates from 1.2
  "summary 2.1":       ["strategy", "4.1.0", "The mandate"],                            // CUT as prose; the M&E asset stays in 4.1
  "summary 2.3":       ["analysis", "3.8.2", "The operating conditions"],               // CUT: covered by 2.6, 2.7, 3.8
};

/** Blocks the brief eventually splits. Phase 1 places the whole block; Phase 2 divides it. */
export const SPLITS = [
  ["situation 3.3.5", "data 2.4",      "data 2.6",      "people stay; connectivity joins 2.6"],
  ["reach 3.6.1",     "data 2.6",      "analysis 3.8",  "the facts stay; the digital ceiling is analysis"],
  ["situation 3.3.1", "data 2.8",      "strategy 4.1",  "the record is data; its positioning use is strategy"],
  ["situation 3.3.2", "analysis 3.5",  "delivery 5.8",  "certified results stay; eligibility scenarios are a risk"],
  ["presence 1A.2.5", "analysis 3.9",  "strategy 4.7",  "findings stay; the six fixes are strategy"],
  ["summary 2.2",     "objectives 1.2","-",             "the calendar stays; the slider and poll table are cut"],
  ["situation 3.3.3", "data 2.1",      "annex-county B.1", "the summary stays; the 40-ward list is Annex B"],
];
